const algorithmData = [
  {
    name: 'Bubble Sort',
    slug: 'bubble',
    category: 'sorting',
    description: 'Repeatedly steps through the list, compares adjacent elements, and swaps them if they are in the wrong order. Simple but inefficient for large datasets.',
    timeComplexity: { best: 'O(n)', average: 'O(n²)', worst: 'O(n²)' },
    spaceComplexity: 'O(1)',
    stable: true,
    inPlace: true,
    steps: [
      'Start at the beginning of the array',
      'Compare adjacent elements',
      'Swap if left > right',
      'Move to next pair',
      'Repeat for n-1 passes',
      'Each pass "bubbles" the largest unsorted element to its correct position',
    ],
    useCases: ['Educational purposes', 'Nearly sorted arrays', 'Small datasets'],
    code: {
      python: `def bubble_sort(arr):\n    n = len(arr)\n    for i in range(n - 1):\n        for j in range(n - i - 1):\n            if arr[j] > arr[j + 1]:\n                arr[j], arr[j + 1] = arr[j + 1], arr[j]\n    return arr`,
      javascript: `function bubbleSort(arr) {\n  const n = arr.length;\n  for (let i = 0; i < n - 1; i++) {\n    for (let j = 0; j < n - i - 1; j++) {\n      if (arr[j] > arr[j + 1]) {\n        [arr[j], arr[j + 1]] = [arr[j + 1], arr[j]];\n      }\n    }\n  }\n  return arr;\n}`,
    },
  },
  {
    name: 'Selection Sort',
    slug: 'selection',
    category: 'sorting',
    description: 'Divides the array into a sorted and unsorted region. Repeatedly selects the minimum element from the unsorted region and moves it to the sorted region.',
    timeComplexity: { best: 'O(n²)', average: 'O(n²)', worst: 'O(n²)' },
    spaceComplexity: 'O(1)',
    stable: false,
    inPlace: true,
    steps: [
      'Find the minimum in unsorted portion',
      'Swap it with the first unsorted element',
      'Expand sorted boundary by one',
      'Repeat until all sorted',
    ],
    useCases: ['Small datasets', 'Memory-constrained systems', 'When writes are expensive'],
    code: {
      python: `def selection_sort(arr):\n    n = len(arr)\n    for i in range(n - 1):\n        min_idx = i\n        for j in range(i + 1, n):\n            if arr[j] < arr[min_idx]:\n                min_idx = j\n        arr[i], arr[min_idx] = arr[min_idx], arr[i]\n    return arr`,
      javascript: `function selectionSort(arr) {\n  const n = arr.length;\n  for (let i = 0; i < n - 1; i++) {\n    let minIdx = i;\n    for (let j = i + 1; j < n; j++) {\n      if (arr[j] < arr[minIdx]) minIdx = j;\n    }\n    [arr[i], arr[minIdx]] = [arr[minIdx], arr[i]];\n  }\n  return arr;\n}`,
    },
  },
  {
    name: 'Insertion Sort',
    slug: 'insertion',
    category: 'sorting',
    description: 'Builds a sorted array one element at a time by inserting each new element into its correct position within the already-sorted portion.',
    timeComplexity: { best: 'O(n)', average: 'O(n²)', worst: 'O(n²)' },
    spaceComplexity: 'O(1)',
    stable: true,
    inPlace: true,
    steps: [
      'Consider first element as sorted',
      'Pick next element (key)',
      'Compare key with sorted elements from right to left',
      'Shift larger elements one position right',
      'Insert key at correct position',
    ],
    useCases: ['Nearly sorted arrays', 'Online sorting (streaming data)', 'Small arrays'],
    code: {
      python: `def insertion_sort(arr):\n    for i in range(1, len(arr)):\n        key = arr[i]\n        j = i - 1\n        while j >= 0 and arr[j] > key:\n            arr[j + 1] = arr[j]\n            j -= 1\n        arr[j + 1] = key\n    return arr`,
      javascript: `function insertionSort(arr) {\n  for (let i = 1; i < arr.length; i++) {\n    const key = arr[i];\n    let j = i - 1;\n    while (j >= 0 && arr[j] > key) {\n      arr[j + 1] = arr[j];\n      j--;\n    }\n    arr[j + 1] = key;\n  }\n  return arr;\n}`,
    },
  },
  {
    name: 'Merge Sort',
    slug: 'merge',
    category: 'sorting',
    description: 'A divide-and-conquer algorithm that splits the array in half, recursively sorts each half, then merges the sorted halves. Guarantees O(n log n) in all cases.',
    timeComplexity: { best: 'O(n log n)', average: 'O(n log n)', worst: 'O(n log n)' },
    spaceComplexity: 'O(n)',
    stable: true,
    inPlace: false,
    steps: [
      'Divide array into two halves',
      'Recursively sort left half',
      'Recursively sort right half',
      'Merge two sorted halves',
      'Compare elements from each half during merge',
    ],
    useCases: ['Large datasets', 'External sorting', 'Linked lists', 'When stability is required'],
    code: {
      python: `def merge_sort(arr):\n    if len(arr) <= 1:\n        return arr\n    mid = len(arr) // 2\n    left = merge_sort(arr[:mid])\n    right = merge_sort(arr[mid:])\n    return merge(left, right)\n\ndef merge(left, right):\n    result = []\n    i = j = 0\n    while i < len(left) and j < len(right):\n        if left[i] <= right[j]:\n            result.append(left[i]); i += 1\n        else:\n            result.append(right[j]); j += 1\n    return result + left[i:] + right[j:]`,
      javascript: `function mergeSort(arr) {\n  if (arr.length <= 1) return arr;\n  const mid = Math.floor(arr.length / 2);\n  const left = mergeSort(arr.slice(0, mid));\n  const right = mergeSort(arr.slice(mid));\n  return merge(left, right);\n}\nfunction merge(l, r) {\n  const res = []; let i = 0, j = 0;\n  while (i < l.length && j < r.length)\n    res.push(l[i] <= r[j] ? l[i++] : r[j++]);\n  return [...res, ...l.slice(i), ...r.slice(j)];\n}`,
    },
  },
  {
    name: 'Quick Sort',
    slug: 'quick',
    category: 'sorting',
    description: 'Selects a pivot element and partitions the array around it. Elements smaller than pivot go left, larger go right. Recursively sorts partitions.',
    timeComplexity: { best: 'O(n log n)', average: 'O(n log n)', worst: 'O(n²)' },
    spaceComplexity: 'O(log n)',
    stable: false,
    inPlace: true,
    steps: [
      'Choose a pivot (last element)',
      'Partition: move elements < pivot to left, > pivot to right',
      'Place pivot in its final sorted position',
      'Recursively sort left subarray',
      'Recursively sort right subarray',
    ],
    useCases: ['General purpose sorting', 'In-memory sorting', 'When average case matters most'],
    code: {
      python: `def quick_sort(arr, low=0, high=None):\n    if high is None: high = len(arr) - 1\n    if low < high:\n        pi = partition(arr, low, high)\n        quick_sort(arr, low, pi - 1)\n        quick_sort(arr, pi + 1, high)\n    return arr\n\ndef partition(arr, low, high):\n    pivot = arr[high]\n    i = low - 1\n    for j in range(low, high):\n        if arr[j] <= pivot:\n            i += 1\n            arr[i], arr[j] = arr[j], arr[i]\n    arr[i + 1], arr[high] = arr[high], arr[i + 1]\n    return i + 1`,
      javascript: `function quickSort(arr, low = 0, high = arr.length - 1) {\n  if (low < high) {\n    const pi = partition(arr, low, high);\n    quickSort(arr, low, pi - 1);\n    quickSort(arr, pi + 1, high);\n  }\n  return arr;\n}\nfunction partition(arr, low, high) {\n  const pivot = arr[high]; let i = low - 1;\n  for (let j = low; j < high; j++)\n    if (arr[j] <= pivot) { i++; [arr[i],arr[j]]=[arr[j],arr[i]]; }\n  [arr[i+1],arr[high]]=[arr[high],arr[i+1]];\n  return i + 1;\n}`,
    },
  },
  {
    name: 'Binary Search',
    slug: 'binary',
    category: 'searching',
    description: 'Efficiently finds a target in a sorted array by repeatedly halving the search space. Each iteration eliminates half the remaining candidates.',
    timeComplexity: { best: 'O(1)', average: 'O(log n)', worst: 'O(log n)' },
    spaceComplexity: 'O(1)',
    stable: null,
    inPlace: true,
    steps: [
      'Set left = 0, right = n-1',
      'Calculate mid = (left + right) / 2',
      'If arr[mid] == target, found!',
      'If arr[mid] < target, search right half',
      'If arr[mid] > target, search left half',
      'Repeat until found or left > right',
    ],
    useCases: ['Sorted arrays/lists', 'Dictionary lookups', 'Finding insertion point', 'Range queries'],
    code: {
      python: `def binary_search(arr, target):\n    left, right = 0, len(arr) - 1\n    while left <= right:\n        mid = (left + right) // 2\n        if arr[mid] == target:\n            return mid\n        elif arr[mid] < target:\n            left = mid + 1\n        else:\n            right = mid - 1\n    return -1`,
      javascript: `function binarySearch(arr, target) {\n  let left = 0, right = arr.length - 1;\n  while (left <= right) {\n    const mid = Math.floor((left + right) / 2);\n    if (arr[mid] === target) return mid;\n    else if (arr[mid] < target) left = mid + 1;\n    else right = mid - 1;\n  }\n  return -1;\n}`,
    },
  },
];

module.exports = algorithmData;
